project_id = "jwchmdivuwgfjrwvgtia"

[functions.smart-assign]
verify_jwt = true

[functions.send-closure-report]
verify_jwt = false

[functions.analyze-financial-data]
verify_jwt = true

[functions.process-financial-import]
verify_jwt = true

[functions.analyze-import-ai]
verify_jwt = true

[functions.analyze-csv-columns]
verify_jwt = true

[functions.send-invitation]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = true

[functions.send-test-email]
verify_jwt = true

[functions.send-inventory-email]
verify_jwt = true
